language: java
jdk:
- openjdk7
- oraclejdk8
before_install:
- cp ./settings.xml ~/.m2/
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "openjdk7" ]] &&
  { mvn clean deploy -DskipTests; };'
- mvn clean verify cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
    on_success: always
